### ISSUE TITLE
Allow to silently ignore symlinks

### ISSUE THREAD

**Issue by azrdev** [bcpierce00/unison#590] opened 2021-10-04 08:56 UTC
I'm syncing between a Linux filesystem and a Windows one (smb with `mount.cifs`), thus symlinks are not supported.
They appear in the synchronization list and summary, though, as failed transfers, which makes for some noise I have to filter manually when reviewing the changes.

Please add a flag `-links ignore` to just skip symlink syncing when it's known in advance they are not supported. `-links false` skips them, but yields an error "is a symbolic link".

**Comment by chrisl8** [comment] 2022-01-14 23:45
I wonder if PR #535 might ultimately address this? If symlinks **can** work on Windows, then can we stop getting the errors?

I'm not actually sure if the "is a symbolic link" is an error or just that the code is set to always whine about the things you asked it to ignore?

Either way, at least that PR is a useful reference for someone attempting to address this issue in the code, such as myself.

**Comment by gdt** [comment] 2022-01-15 00:46
@chrisl8 Can you test the situation that you think @azrdev is encountering, on 2.51.5?    I don't use windows at all, and I'm really unclear on the sequencing of #535 and this report.

**Comment by azrdev** [comment] 2022-01-17 12:38
Actually I'm on linux, sorry that I didn't mention it explicitly.

**Comment by chrisl8** [comment] 2022-01-17 16:54
Sorry, upon reflection I realized I was confusing two experiences together.

The PR did help me understand the code, but this issue seems to be merely a message about every skipped simlink, not errors.

I wasn't initially sure if those messages were errors or not. I can see now that they are not.

This issue does affect me though. When I skip simlinks on a large sync I get hundreds of the messages, making it hard to see what is happening.

I intend to dig into the code and attempt an update to fix this soon, if nobody else gets to it first.

**Comment by tleedjarv** [comment] 2022-01-17 17:37
This is not as easy to solve as it may look like initially. A change in preferences (either by going for the solution suggested by the original reporter (to add a `-links ignore` flag) or by adding a separate new preference) is a version-incompatible change.

Just recently a PR was merged, which makes changes like this finally possible while keeping backwards compatibility. With the "features" mechanism introduced by that PR, a solution with a separate new preference is by far the easiest.

I can't judge if this is a good thing to have (it seems that there are several users who would like to see it) and I can't judge if it's really worth adding yet another preference (or a new option to existing preference), but I'm willing to quickly produce a prototype to demonstrate the solution.

**Comment by tleedjarv** [comment] 2022-01-17 19:17
A draft PR is opened now, demonstrating a potential solution. I'm happy to continue developing and enhancing the solution as long as users requesting this feature are willing to do rigorous testing (incl. GUI and compatibility with previous versions).

**Comment by chrisl8** [comment] 2022-01-24 14:27
I will test it. I'll grab this now and build it and test it via CLI to start with.

As to "rigorous testing", I  am willing to run any tests that you suggest.

**Comment by tleedjarv** [comment] 2022-01-24 17:50
Thank you for testing @chrisl8 

As for required testing, I am no authority either, I'm just a contributor like you. What I would consider a minimum amount of testing to mark the PR as ready for review would be as follows:
* test on Windows (both as a client and a server)
* test against versions without this PR, that is <= 2.51.5 but >= 2.51.0
* test for any regressions when _not_ using the new preference
* test for sane operation and absence of regressions with `links` preference values `true` and `false`
* test for sane operation and absence of regressions with `follow` preference
(note that the testing does not have to be done against your production setup)

I can't be more precise; basically go with some exploration, walking through various syncs of replicas with and without links. Two different sets of replicas could be prepared, one with links and one without, and then various combinations of configurations run on these replicas. It is not a terrible amount of work but it's still some work to be done and that's why I'm asking for potential users to step in.

The changes are not very invasive, so a succesful run with various preference combinations on both Linux and Windows is a good sign.

**Comment by tleedjarv** [comment] 2022-01-24 18:04
For those willing to help out with testing, you can find binaries with this PR at https://github.com/bcpierce00/unison/actions/runs/1741345202 (you have to be logged in to download).

**Comment by tleedjarv** [comment] 2022-02-21 15:22
I rebased and updated the PR with a slightly better solution. If you are using the previous one from the PR, this one is not compatible with that (but you will see a relevant error message if you try to mix and match different versions).

If you are looking for CI-built binaries for testing, go to https://github.com/bcpierce00/unison/actions/runs/1876862706

**Comment by chrisl8** [comment] 2022-02-21 18:50
@tleedjarv

I am using the new code now with "-links ignore". I appreciate the helpful error as I had already added "-ignorelinks" to several scripts and it was very easy to see what to change.

So far it is working fine. I will report back here if I encounter any issues during my daily usage.

**Comment by gdt** [comment] 2022-02-27 14:14
I wonder if there is a larger issue with unison from A to B where some filesystem features do not work on B, either POSIX-required features or optional features (eg ACL), and what the desired semantics are.   I would really like to see something reasonable happen by default, rather than have users set lots of options. 

This could end up with a lot of prefs having values no/ifsupported/yes and defaulting to ifsupported.   I don't want to deal with this until 2.52.0 is out though, but am happy for big-picture discussion to start, probably best on unison-users@.

**Comment by tleedjarv** [comment] 2022-02-27 20:46
I very much agree with this idea (and I think it is difficult to implement reliably everywhere) - if the reasonable thing can be done without asking the user then it should be the default.

But coming back to this very issue here, the question is, why report errors in the first place? Specifically for symlinks (and I think only for symlinks in current implementation), this issue was started because the user has no way of escaping the error messages.

The `links` preference does have the no/ifsupported/yes values and it does default to ifsupported, exactly as you propose. And yet, the user is bombarded with error messages if symlinks are not supported.

Perhaps the solution to this issue is very simple. Just silence the errors (in case of values no and ifsupported->no)? I can see some point of error messages with the default setting. But what is the value of the error messages if the user has explicitly said 'I don't want to sync links'?

**Comment by chrisl8** [comment] 2022-02-27 22:08
For me I am very happy now if I can just truly "ignore" the links, without any console output, when specifically requested, as the current PR accomplishes.

I'm not sure how the OP feels, but that does seem to be the spirit of this particular issue, just being able to silence the notices when asked to ignore links.

**Comment by chrisl8** [comment] 2022-03-18 19:54
I'm still using this daily without issue. Is there anything else I can do to contribute to help move this toward being merged?

**Comment by tleedjarv** [comment] 2022-03-21 08:52
I would prefer a discussion on the mailing list. `-links false` produces the error messages but is there anyone who actually wants these error messages? My preferred solution is to change `-links false` to ignore symlinks, unless there is someone with a good case of wanting/needing the error messages.

**Comment by tleedjarv** [comment] 2022-07-26 10:25
I've pushed a new solution which makes `-links=false` ignore symlinks. You can get binaries for testing at https://github.com/bcpierce00/unison/actions/runs/2738666970 Please test!

This issue is rather more difficult than it seems on the surface. There are many big questions around this feature and the `links` preference in general. I've discussed this with @gdt and my current best proposal is in PR #623. "Best", as in, the least amount of code change, the least amount of semantical change, yet sufficient to close #590. The PR makes no attempt at going further than that.

**Comment by tleedjarv** [comment] 2022-09-02 09:27
@chrisl8 @azrdev any chance you could test and report the results? This needs confirmations to have a chance of being in the next release.

**Comment by chrisl8** [comment] 2022-09-02 14:36
Sorry, I missed the update in July until now.

I have pulled down this new code this morning.
I set my argument to `-links false` instead of `-links ignore`.
(It seems to work the same way with either `-links ignore` or `-links false` now.)
I have tested it several times.
The output is now clean, as with the previous candidate, with no errors when skipping links.
It looks good to me. Does what is required without any apparent side effects.

**Closed** 2022-09-08 22:29 UTC
Labels: enhancement, impact-low, feedback, effort-medium, windows
