### ISSUE TITLE
Apple Silicon M1 ARM binaries ...

### ISSUE THREAD

**Issue by bkervaski** [bcpierce00/unison#617] opened 2021-12-27 14:29 UTC
Hi All!

More of a feature request I think than an issue ... any efforts for a native Apple Silicon binary?  The x86 works fine under Rosetta, but a native binary would be great.

I'm going to see if I can get it compiled today, but opening this in hopes of having an M1 binary as part of the standard releases, we use it extensively.

**Comment by gdt** [comment] 2021-12-27 15:40
Note that releases are source.    CI binaries are useful to many, but technically they aren't part of the release.

github does not have any support for Apple arm64, or really much beyond a highly limited set.
See #445.  So there is no path to doing this, and I'm closing it as not just wontfix but cantfix.  If I'm wrong and there is support, a PR to add a version is something I'd review and either merge or talk about on unison-hackers.  For CI purposes, adding a macos/aarch64 build would be very useful.   Having all the ocaml versions becomes problematic as the the limited-version limited-os limited-cpu issue is adddressed.  But for now 4.08 and up is probably ok, in the theoretical case that there is macos/aarch64 support.

There is some notion of external CI runners, but I don't understand in detail, and am uninterested in dealing with it because it's still a proprietary system, and it's still limited to a handful of operating systems.  But if you figure it out and set up a runner and want to integrate it for CI, and submit a PR to use it, I'll review that and merge it if it seems ok.  I do not expect to be comfortable hosting external runner CI artifacts, but they could get a pointer in the Wiki of "other people's builds".

Certainly if unison fails to build, file a bug or ask on unison-users.   I've been building unison on NetBSD/earmv7hf-el, so it's known that it works on at least one non-x86 system.

**Closed by gdt** 2021-12-27 15:40 UTC
Labels: wontfix, macOS, project

**Comment by bkervaski** [comment] 2021-12-27 15:51
Understood, thanks :)

**Comment by bkervaski** [comment] 2021-12-27 15:54
Just an anecdotal note ... it does compile and run just fine on Apple Silicone with ocaml 4.12.0 with the 2.51.3 ... no issues upon initial testing

**Comment by gdt** [comment] 2021-12-27 16:11
Thanks for confirming it builds.  I suggest you try 2.51.5 instead of .3, as it has a large number of fixes, and should be archive-format and wire-format compatible.  But I don't  expect any build regressions from those changes.

**Comment by avollmerhaus** [comment] 2021-12-28 12:42
To add another anecdotal note here, I've been using unison on ppc64le for quite some time and it worked fine, too.
So that's another "known" (if you take my word for it, not sure for how much that counts - I've not been running the GUI, for example) non-x86 system.

**Comment by mathiaswagner** [comment] 2023-10-04 05:41
Does https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/ change things?
