### ISSUE TITLE
make NATIVE=false fails

### ISSUE THREAD

**Issue by bcrowell** [bcpierce00/unison#753] opened 2022-06-14 03:02 UTC
I have a machine where I was unable to get ocamlopt working, so I did this:

make UISTYLE=text NATIVE=false

The result was:

/usr/bin/ld: osxsupport.o: in function `getFileInfos':
/home/bcrowell/c/unison/src/osxsupport.c:83: undefined reference to `unix_error'
/usr/bin/ld: osxsupport.o: in function `setFileInfos':
/home/bcrowell/c/unison/src/osxsupport.c:134: undefined reference to `unix_error'

**Comment by tleedjarv** [comment] 2022-06-14 05:56
You are using OCaml trunk. A commit breaking Unison was merged there less than 24 hours ago. The issue is known and will be fixed soon.

Meanwhile, please use a released OCaml version. If you want, you can leave the ticket open and rename it. The actual issue is that building with OCaml trunk (the upcoming 5.0) fails.

**Comment by gdt** [comment] 2022-06-14 10:51
The issue described in this issue is fixed, as far as I can tell.

**Closed by gdt** 2022-06-14 10:51 UTC
Labels: portability
