### ISSUE TITLE
On windows, unison fails to deal with appledouble on paths like D: (leading to sync failure from macOS unless rsrc=false)

### ISSUE THREAD

**Issue by sboukortt** [bcpierce00/unison#607] opened 2021-12-05 10:05 UTC
Hi,

First of all, I would like to thank you for this very useful piece of software. I have been using it for, I think, over ten years, to keep my data coherent across my personal machines.

The problem that I am newly encountering is that, although the following profile works well for Windows <-> Windows or Windows <-> Linux synchronization:

```
root = C:/Users/Sami/  # or /home/sami
root = socket://192.168.1.10:1234/D:/

Path = Documents
Path = Music
# etc.
```

If the machine with the first root runs macOS instead (whether as the server or the client), attempting the same thing displays an error message saying: “The path D:/ is a root directory”. I have not found a way to specify the second root (`…/D:`, `…/D:\`) that avoids this.

It can be worked around by ssh’ing into WSL (`root = ssh://sami@192.168.1.10//mnt/d/` + `fat = true`), but it would perhaps be good not to have to rely on that.

Thanks again.

**Comment by gdt** [comment] 2021-12-05 14:09
Please ask about this on the unison-users list, and provide more details.   I am not able to conclude from your report that there is a failure to follow specs in unison, partly because I'm not clear on the specs regarding windows (I don't use windows).   i do not understand why you think using windows-style volume names (D:) is sensible on a non-windows computer.

**Comment by sboukortt** [comment] 2021-12-05 14:19
> i do not understand why you think using windows-style volume names (D:) is sensible on a non-windows computer.

The second machine involved in the sync _is_ a Windows computer.

**Comment by tleedjarv** [comment] 2021-12-05 14:40
Please try adding `rsrc = false` to the profile and see if that makes a difference.

**Comment by sboukortt** [comment] 2021-12-05 15:10
Thanks, it does! With that option, it works without issue.

**Comment by tleedjarv** [comment] 2021-12-05 15:33
This seems to be a bug in the code that looks for AppleDouble files. If you are not using resource forks on macOS then keeping `rsrc = false` can be the permanent solution for you (but it's still just a workaround, so keep the issue open).

**Comment by gdt** [comment] 2021-12-05 15:44
@tleedjarv Perhaps you can open an issue that you think describes the bug, and we can close this?   It sort of sounds like "unison on windows doesn't realize it can't cope with mac resource forks and gives a confusing/wrong error", but I am not sure I followed exactly.

**Comment by tleedjarv** [comment] 2021-12-05 16:42
I think this issue is accurate.
According to my analysis, the cause is this: when macOS is included in a sync (either server or client) then `rsrc` preference gets enabled automatically; when `rsrc` preference is enabled on filesystems which don't support macOS resource forks (such as FAT or NTFS in this case), AppleDouble files are used as a fallback. The bug is in the code checking for existence of an AppleDouble file -- it rejects a root dir when constructing a path for the AppleDouble file.

Relevant code here (`Fspath.findWorkingDir` being the cuplrit):
https://github.com/bcpierce00/unison/blob/b74f367532e930396e420235e5809cdeaaabbefc/src/osx.ml#L254-L260
(similar code is in function `setFileInfos`)

**Closed** 2022-08-01 00:34 UTC
Labels: defect, impact-low, effort-medium, windows
