### ISSUE TITLE
Files on old RHEL remote perceived as deleted (either they were, or perhaps a unison issue)

### ISSUE THREAD

**Issue by lieh1203** [bcpierce00/unison#673] opened 2022-03-09 08:40 UTC
Hi,
closed by  [#618](https://github.com/bcpierce00/unison/issues/618)
I got the debugging information.
46031cd405b929f7db40901040de4a38.tif is a missing file, and I found  some deletion operations is in the fourth picture.

![1](https://user-images.githubusercontent.com/34055613/157401347-200eaef9-733c-46a5-b2ae-750361892f73.png)

![2](https://user-images.githubusercontent.com/34055613/157401375-d05b8ca0-76f9-4627-97a0-d1cb0f6292eb.jpg)

![3](https://user-images.githubusercontent.com/34055613/157401417-d2d3480d-dd3b-40f2-93f6-2bb1b9754de2.png)

![4](https://user-images.githubusercontent.com/34055613/157401430-74ee3a18-7169-4b3b-89b8-25ec4c97c755.jpg)

Thanks, Any help would be appreciated.

**Comment by lieh1203** [comment] 2022-03-09 10:06
> 



> This is interesting. It seems like the first sync succeeds and then on a subsequent sync the file is not found.
> 
> Are you able to run this scenario again, this time only with the following debug flags: `update+` and `fileinfo+`. You may do it by adding on the command line: `-debug update+ -debug fileinfo+` or by adding in the profiles
> 
> ```
> debug = update+
> debug = fileinfo+
> ```
Thanks!
debug = update+
debug = fileinfo+
add to default.prf ?
need to restart Unison?

**Comment by tleedjarv** [comment] 2022-03-09 10:09
Yes, add to default.prf. Yes, do a restart.

**Comment by lieh1203** [comment] 2022-03-09 10:36
> 



> Yes, add to default.prf. Yes, do a restart.

@[tleedjarv](https://github.com/tleedjarv)
Thank you. The configuration file has been changed, but it can't see the debug message until the next time the file is lost.
It happens randomly.

**Comment by lieh1203** [comment] 2022-04-21 05:00
@[tleedjarv](https://github.com/tleedjarv)

I adding on the command line: -debug update+ -debug fileinfo+, and got new debugging information.
e46e17c5d749ce5cdb1e9a16e4ea471b.doc、e062721699586fa08a9db785e69ddaab.pdf are two new missing files, and some deletion operations are recorded in the following log.

![log1](https://user-images.githubusercontent.com/34055613/164374733-32ef5935-794e-4012-a5f8-269cce589d06.jpg)

![log2](https://user-images.githubusercontent.com/34055613/164374550-6ae48a54-4a70-400d-8067-0be9c8380341.jpg)

![log3](https://user-images.githubusercontent.com/34055613/164374563-ae6089ff-587e-4f3d-87a3-3b0e30cf606e.jpg)

**Comment by tleedjarv** [comment] 2022-04-21 13:17
Thank you for the additional information. Unfortunately, there is nothing that shows any wrongdoing on Unison's part.

What the logs show happening, is:

1. In one replica (the remote one) Unison _can no longer see_ the file, thus it assumes it was deleted (this is `buildUpdate -> Deleted` entry in the log; Unison does not delete anything itself here!).
2. In the other replica the file is still there and Unison, having detected a deletion in the first replica, propagates the deletion to the other replica (correctly, as designed). This is the `[BGN] Deleting ...` entry in the log where Unison is actually deleting the file.

To clarify the "_can no longer see_" from point 1, Unison considers a file/dir missing if the `stat` syscall returns an error `ENOENT` or `ENOTDIR`. On Windows, this corresponds to errors `ERROR_FILE_NOT_FOUND`, `ERROR_PATH_NOT_FOUND`, `ERROR_INVALID_DRIVE`, `ERROR_NO_MORE_FILES`, `ERROR_BAD_NETPATH`, `ERROR_BAD_NET_NAME`, `ERROR_BAD_PATHNAME`, `ERROR_FILENAME_EXCED_RANGE`.

If `stat` returns some other error (for example, lacking permissions) then that will be logged an displayed to the user, so based on current logs it is safe to assume that there was no other error.

Based on all the information received so far, Unison is working properly -- it just syncs the deletion to the other root -- but the initial deletion in the first root is not Unison's doing. So, yes, Unison deletes files on one root but **only as a response to files having been deleted in the other root**. Someone or something external has deleted the files in one of the roots first (the remote root in case of these latest logs).

Do you have any audit log information for delete events regarding files on the remote root? For example, what does audit log say for file e062721699586fa08a9db785e69ddaab.pdf ?

Finally, you may want to look into the `nodeletion` preference, which prevents Unison from propagating deletions to the other root. But that may not suit your synchronization goals.

**Comment by gdt** [comment] 2022-04-21 14:07
I've retitled this because evidence to date suggests this is not a unison bug.
I haven't really paid attention because the debug logs are screenshots instead of text - I find them hard to read and I'm not going to try.

What's missing is knowing what has happened on the other side.  I always want to reduce complexity, so I would suggest
 * disabling watch/repeat
 * disabling auto
 * writing a script to take a census of each side before syncing.  Perhaps just "ls -lRa".  Perhaps  "rsync -avn".
 * Turn on any auditing you can on the remote, that would capture all unlinks.
 * disable anything you can on that system that could possibly do this.
 * after the first sync, periodically run the census program and sync
 * or, run unison to sync, and if it reports any deletions, ^C and run the census program.


Also, please read https://github.com/bcpierce00/unison/wiki/Reporting-Bugs-and-Feature-Requests 
This bug report does not include unison version,  operating  system version, filesystem types, and how unison is being run.
Overall it feels more appropriate for the mailinglist.

**Comment by lieh1203** [comment] 2022-04-22 03:40
> Unison's
@[tleedjarv](https://github.com/tleedjarv)
Thanks! 
This is the redhat audit log from a previous post.

![audit log](https://user-images.githubusercontent.com/34055613/164591586-fa2ccc76-0620-462d-bd88-d13c7b114540.png)

**Comment by lieh1203** [comment] 2022-04-22 04:42
@[gdt](https://github.com/gdt)

thanks!
Unison is installed on the bank's system, so we can only take a screenshot and can't get the log file.

The software version is as follows:
Unison: 2.51.2
Inotify: 3.14
redhat: 7.9
filesystem types: xfs

The synchronization mechanism is:
Synchronize in Unison + Inotify mode. As long as there are create, delete, modify and move operations, file synchronization will be triggered.

**Comment by tleedjarv** [comment] 2022-04-22 05:59
> This is the redhat audit log from a previous post. It was found in the log that some files were deleted by Unison.

You have to find the audit log for the latest case that you posted in comment https://github.com/bcpierce00/unison/issues/673#issuecomment-1104709883

Unison _does_ delete the file on one machine because it is propagating a deletion from the other machine (this is by design, this is how it is expected to work). But the deletion on the other machine does not seem to be done by Unison, based on all the information we see so far.

If you can see in the audit logs what happened specifically to file e062721699586fa08a9db785e69ddaab.pdf for example, that would give a needed clue. Yes, on one server it should show that it was deleted by the unison process. But we are interested on how it got deleted on the _other server_ (the one called CLCISAPOC0A in the logs).

**Comment by gdt** [comment] 2022-04-22 11:22
Generally debugging requires the cooperation of system administrators on both sides.    I'm still not going to look at screenshots, and it's starting to seem like you need a consultant -- the issue tracker is not a support forum.

2.51.2 is old.  To be allowed to stay in the tracker, you will need to update to the current version, which today is 2.52.0, on both sides.

I gave you advice to stop using the watcher and repeat mode, and to check the two sides for missing remote files before running unison.

So I'm going to close this as not meeting issue tracker standards.  If you can do all of:
  - update both sides to unison 2.52.0
  - get logs in text (so they are readable and searchable)
  - run unison without watcher/repeat/auto (and if that never shows the missing issue but turning on one of them does, that's interesting)
  - compare the trees by other than unison first (or after, if you don't use auto and exit instead of syncing)
 
you are welcome to file a new bug.    And you should feel free to ask for help on the users mailinglist.

**Closed by gdt** 2022-04-22 11:22 UTC
Labels: discuss, feedback

**Comment by lieh1203** [comment] 2022-04-22 14:40
@[tleedjarv](https://github.com/tleedjarv)

CLCISAPOC0A is the production server.
Users only upload attachments on the production server, and another machine is disaster recovery server, Usually it cannot be accessed.
Thank you!
I will ask for help on the users mailinglist.
