### ISSUE TITLE
macOS apps rejected because of "cltool" (to be closed as a dup)

### ISSUE THREAD

**Issue by TravellerSam** [bcpierce00/unison#462] opened 2021-01-06 20:06 UTC
Unison apps for macOS after extracting are not executable, OS telling that the app is damaged.

<img width="260" alt="macOS apps damaged" src="https://user-images.githubusercontent.com/872730/103814912-d2e25f00-5062-11eb-8b10-4dd94cf4a3f1.png">

Tried with:
Unison-v2.51.4_rc1.ocaml-4.11.1.macos-10.15.app.tar.gz 
Unison-v2.51.4_rc1.ocaml-4.10.1.macos-10.15.app.tar.gz

macOS 11.1
Downloaded with Firefox 84 or Safari 14
Extracted with the system's Archive Utility or The Unarchiver

**Comment by gdt** [comment] 2021-01-06 23:40
Thanks - to make progress someone needs to figure out what is actually wrong.  Surely there is some debugging mechanism to give a more useful error message, that someone who uses GUI apps on macOS knows about!

**Comment by tleedjarv** [comment] 2021-01-10 13:30
I wonder if this is the quarantine. See https://github.com/bcpierce00/unison/issues/422#issuecomment-722262320 and https://github.com/bcpierce00/unison/wiki/CI-Binary-instructions

**Comment by TravellerSam** [comment] 2021-01-10 15:07
Thanks @tleedjarv, `xattr -cr Unison.app` workaround solves it.

**Comment by tleedjarv** [comment] 2021-01-10 19:48
I have understood that there's not much we can do about this currently (as it requires signing the app). So, close the issue?

**Comment by gdt** [comment] 2021-01-11 15:44
The xattr incantation is already in the wiki.   Please file a bug with apple that the error message is not useful!

**Comment by zuckschwerdt** [comment] 2021-01-21 07:54
The problem is an unsigned file:
```
$ codesign --verify --deep --strict --verbose=2 ~/Downloads/Unison.app
~/Downloads/Unison.app: a sealed resource is missing or invalid
file added: ~/Downloads/Unison.app/Contents/MacOS/cltool
```

Remove the `cltool` and it works:
```
$ rm ~/Downloads/Unison.app/Contents/MacOS/cltool
$ codesign --verify --deep --strict --verbose=2 ~/Downloads/Unison.app
~/Downloads/Unison.app: valid on disk
~/Downloads/Unison.app: satisfies its Designated Requirement
```

**Comment by gdt** [comment] 2021-01-21 17:10
@zuckschwerdt  Could you file a new issue about the cltool finding?   To the extent you understand, please explain why cltool is present in the first place, and if removing it has any negative consequences.   It sounds like a merge request could make things better.

(I am not aware of anyone in unison performing signing in any explicit way, but I am unfamiliar with that kind of macOS builds, only having used macs as regular computers.)

**Comment by gdt** [comment] 2021-01-21 17:26
This issue should be closed as a dup once we have an issue that explains what's really going on.

**Comment by zuckschwerdt** [comment] 2021-01-21 18:21
Hi Greg, what a small world. Thanks for picking this up, follow up in #469

**Comment by gdt** [comment] 2021-01-21 18:26
Thanks, and indeed I often find that the world appears smaller than one might expect.  Closing this as a dup since the history is not useful now that we (you - thanks!) understand better.

**Closed by gdt** 2021-01-21 18:26 UTC
Labels: GUI, feedback, macOS
