### ISSUE TITLE
Add option to skip synchronization of duplicate files

### ISSUE THREAD

**Issue by eugenesan** [bcpierce00/unison#22] opened 2016-06-22 13:37 UTC
Currently Unison backs up all "changed" files which is great as a default behavior but it would helpful to have an option to exclude duplicate files from the backup, such as:
- Moved files
- Copied files
- Files with only metadata being changed

On other hand, some people might prefer linking (symlink/hardlink) those files instead of just excluding them from the backup.

**Comment by bcpierce00** [comment] 2016-06-23 13:04
Happy to review a pull request.

**Comment by gdt** [comment] 2020-10-14 00:48
The notion of what is "duplicate" is unclear, and given that this feature request is 4 years old, I'm going to close it.  Feel free to discuss the intended behavior on the mailinglist to see if there is consensus that others would want it, if you are inclined to write the code and submit it.

**Closed by gdt** 2020-10-14 00:48 UTC
Labels: effort-high, enhancement, wontfix
