### ISSUE TITLE
CLI-only package

### ISSUE THREAD

**Issue by liyishuai** [bcpierce00/unison#793] opened 2022-09-13 08:15 UTC
The current Unison package requires lablgtk, making it incompatible with some Linux distributions per https://github.com/coq/opam-coq-archive/pull/2303#issuecomment-1245043524. Consider releasing a CLI-only package.

#671 should fix this.

**Comment by palmskog** [comment] 2022-09-13 09:01
To be more precise, I think the problem is with lablgtk2 in Debian Bullseye - we have the following comment in our CI config:
```
apt-get install libgtksourceview2.0-dev -y || true # gone with Debian bullseye
```
However, lablgtk3 is what CoqIDE uses, so this should be supported across both lots of Linuxes and Windows and Mac.

**Comment by gdt** [comment] 2022-09-13 11:28
Could you edit this to be clearer?  Unison is source, not binary packages, and I'm guessing you mean the opam/dune files that are checked in.

And, unison has switched to gtk3, so I'm not sure this makes sense against the tip of master.

**Comment by palmskog** [comment] 2022-09-13 11:42
The latest release of `unison` on opam (2.52.0) requires lablgtk2, which is (at least from what I know) not supported in some recent Linux distributions. Hence, the lablgtk2 dependency can be a problem in packaging of projects like that by @liyishuai that depend on unison. If there was a released version of unison with lablgtk3 support (and marked thus in the official opam package), he could add his packages that depend on unison more easily. But the best solution would be if some CLI-only unison package (no dependency on lablgtk at all) was made available via opam.

**Comment by gdt** [comment] 2022-09-13 11:50
The latest release of unison is 2.52.1, so not sure what's up.  But packaging systems are there own thing, and what the opam project does is not really in scope here, just as how pkgsrc, debian, RH, etc. handle unison is their issue.

That said, we are heading to 2.53.0 fairly soon.   Testing of that is always appreciated.

**Comment by palmskog** [comment] 2022-09-13 11:58
The packages available via opam directly (`opam install unison`) are those here, presumably maintained by volunteers: https://github.com/ocaml/opam-repository/tree/master/packages/unison

However, the issue is really unrelated to what exactly is available there, since to even have the possibility of building unison without lablgtk, the source code must have support for this, e.g., via the Dune build system. I presume #671 is a step towards this.

**Comment by gdt** [comment] 2022-10-09 00:39
I still don't entirely follow this.   pkgsrc builds unison without a gui.   So if it's a feature request to change the dune build files that are in the unison source tree, please either edit or open a new PR and say that clearly.  Requests about files in an opam repo should be addressed to them.   (From my point of view, dune is something some people use, and is not the primary build system.)

**Comment by gdt** [comment] 2022-11-15 13:18
I ran 'dune build -p unison'  and got a CLI-only unison executable.    However I see your point that the package file says it needs lablgtk3, even though it actually doesn't.  Is that what you mean?

**Comment by gdt** [comment] 2022-11-15 14:05
Please see https://lists.seas.upenn.edu/pipermail/unison-hackers/2022-November/002061.html and followup on the list.

**Comment by gdt** [comment] 2022-12-02 10:58
I have restated the issue (in a way that future me will understand) in #842.

**Closed by gdt** 2022-12-02 10:58 UTC
Labels: feedback
