### ISSUE TITLE
Using Unison against a SAMBA share creates hidden files

### ISSUE THREAD

**Issue by sur5r** [bcpierce00/unison#573] opened 2021-08-05 15:13 UTC
When syncing to a SAMBA share, the following happens

1. Unison creates a new temporary file (`.unison.X.Y.unison.tmp`)
2. SAMBA recognizes the leading dot and applies the hidden DOS attribute to the file
3. Unison renames the file to its final name
4. The resulting file is hidden while the original file was not.

This is an unfortunate interaction between Unison and a SAMBA setting called `hide dot files` which is enabled by default.

Setting `hide dot files` to `no` prevents this but makes dot files show up as non-hidden on Windows. So a workaround is available but it's not ideal.

While I found places in the code related to attributes and permissions, I could not find the right place to try and patch this.

Open questions on my side:
- Does Unison sync all DOS attributes?
- Does Unison sync them before or after transferring/renaming the file?

**Comment by tleedjarv** [comment] 2021-08-10 16:57
To answer your questions, I don't think Unison syncs any DOS attributes.

What you describe sounds like a bug in Samba.

**Comment by gdt** [comment] 2021-08-13 12:57
I also think this is a samba bug.  I'm not really clear on DOS attributes and am guessing that hidden is a binary attribute on files, and that by default files with this attribute are omitted from directory listings.    I'm further guessing that a file starting with . has nothing to do with being omitted from listings.

If samba is adding a DOS hidden attribute on files that start with . (because those are not displayed by ls on Unix, and therefore it seems they should be marked hidden on DOS?), then it seems it should be adjusting the attribute on rename.

It's really hard to make the argument that unison, when running on Unix, should be doing something DOS-specific.

Also, this seems to be a question, not a bug report, so I'm closing it.  Please use the mailinglist for questions.

**Closed by gdt** 2021-08-13 12:57 UTC
Labels: discuss, feedback, windows

**Comment by sur5r** [comment] 2021-08-13 15:04
Just two points for clarification:
- Unison in this case is running on Windows, so syncing DOS attributes would be well within scope.
- I never said it's a bug. It's an unfortunate interaction between a SAMBA feature that is enabled by default and the way unison creates temporary files.

**Comment by gdt** [comment] 2021-08-13 15:42
Sorry, I misthought and I see your point that samba is on the Unix server and unison was on windows.    (I really do not deal with Windows at all.)

**Comment by 0x6d64** [comment] 2024-06-09 20:06
Sorry to revive that old issue, but could we please reopen this as a feature request?
My situation: Using a Windows10 machine, sync between a local folder (NTFS) and a NAS that is attached using SMB. Whenever I write files to the NAS, they then will have the "hidden" attribute set.

Feature request would be as follows: "Have a parameter, that tells unison to use the pattern `_unison.X.Y.unison.tmp` instead of the normal pattern starting with a dot. This will prevent the SMB from setting the hidden attribute.

**Comment by tleedjarv** [comment] 2024-06-10 08:56
Workarounds are possible, sure. This doesn't mean that the bug should go unfixed. The original ticket is nearly three years old and the same issue has come up separately once or twice since. Has this bug been reported to Samba? Or perhaps there is an explanation as to why this is not a Samba bug?

**Comment by sur5r** [comment] 2024-06-10 09:42
As I wrote earlier: SAMBA recognizes files with a leading dot as hidden files. This is a UNIX-Windows-Compatibility feature. It's not a bug in SAMBA, it's a feature. Which interacts in unfortunate ways with how unison creates temporary files.

**Comment by tleedjarv** [comment] 2024-06-10 09:54
> Which interacts in unfortunate ways with how unison creates temporary files.

But does it really?

I don't use Samba so could you run a little experiment? From Windows Explorer, create a file with a leading dot on a Samba share. It should become hidden, right? This is fine because that's the intent. Now rename that file and remove the leading dot. Is the file hidden or not?

If the file is still hidden then do we agree that it's a bug in Samba?

**Comment by gdt** [comment] 2024-06-10 10:15
In 2021 I argued that this was samba bug.   There has been no explanation of why it isn't.   it seems really clear to me that if samba sets a hidden attribute when a file starting with . is created (seems reasonable but I don't use Windows), then when that file is renamed to not start with ., it should remove the attribute.   Basically the rule about when files get that attribute (automatically) should be expressible in terms of the current state, and not vary based on trajectory.

Nobody has posted a URL to a high-quality samba bug report.  Nobody has posted a reproducer script that shows the SAMBA problem without unison.   I've retitled the bug and suggested that the right action on the unison side is to report it there.

**Comment by gdt** [comment] 2024-06-10 10:24
> As I wrote earlier: SAMBA recognizes files with a leading dot as hidden files. This is a UNIX-Windows-Compatibility feature. It's not a bug in SAMBA, it's a feature. Which interacts in unfortunate ways with how unison creates temporary files.

If samba "recognizes files with a leading dot as hidden", then they will no longer be hidden when renamed.   In order to talk about this we need to be very precise.   Someone needs to write repro scripts, and read the samba sources.

**Comment by tleedjarv** [comment] 2024-06-10 11:47
Mind you, I'm not against adding a workaround if there is no other way (not accepted as a Samba bug or not fixed) but this should be kept as a backup rather than the primary approach. It's also important to keep in mind that the workaround should be automatic while not incurring a performance/functionality penalty for all Windows users.

**Comment by gdt** [comment] 2024-06-10 11:53
I'm much less positive.  One of the cultural bugs in the modern open source world is to view proprietary software, even software that people pay money to run, as unfixable, and to view large open source projects as intractable, perhaps because people only run binaries from GNU/Linux distributions instead of compiling it themselves.

I lean very hard to fixing bugs where the bugs are.   I am against accommodating bugs in other software unless there has been a serious good-faith effort to address them, and one that does not treat other software as intractable.   Without a samba bug report and a repro script, I don't see us making any progress.
