### ISSUE TITLE
Unmounting replica results in a directory delete

### ISSUE THREAD

**Issue by Alexander-Shukaev** [bcpierce00/unison#262] opened 2019-05-05 19:32 UTC
When replica root is a mount point itself, unmounting it may result in a top-level directory deletes in the counterpart replica.  Is there a way to prevent this via options?  Seems like `mountpoint` option is for a different purpose.  Otherwise, this appears as a severe bug.  Does anybody confirm the same problem?

**Comment by Alexander-Shukaev** [comment] 2019-05-05 19:35
By the way, forgot to mention that mounting the first replica back does not result in either a delete of the same top-level directories or in copying those back to the counterpart replica.  Meaning that the data between two is left in this broken state forever.

**Comment by Alexander-Shukaev** [comment] 2019-05-05 19:42
Configuration:

```
auto           = true
batch          = true
confirmbigdel  = true
confirmmerge   = false
copyonconflict = true
copyprog       = rsync --compress --inplace --no-whole-file
copyprogrest   = rsync --compress --inplace --no-whole-file --partial
copyquoterem   = default
copythreshold  = 8192
fastcheck      = default
group          = true
links          = default
log            = true
owner          = true
perms          = -1
prefer         = newer
repeat         = watch
silent         = true
times          = true
ui             = text
watch          = true
```

I'm surprised `confirmbigdel` has no promised effect.

**Comment by gdt** [comment] 2020-01-09 20:52
I agree this is lack of feature is really a bug.  I have two suggestions:
 * have a deletion threshold, on by default, of perhaps 25% of files in a replica
 * place the metadata/archive within the replica, in a directory that is excluded, such as .unison, so that unison on an unmounted replica will cleanly error out

**Comment by tleedjarv** [comment] 2020-10-09 17:58
I am unable to reproduce this issue, also with your posted configuration. `confirmbigdel` works as it should.
You may want to try without `watch` and see if that makes any difference.

If you are still seeing this issue, please report the exact Unison version you are using.

> By the way, forgot to mention that mounting the first replica back does not result in either a delete of the same top-level directories or in copying those back to the counterpart replica. Meaning that the data between two is left in this broken state forever.

This sounds like the Unison process or fswatcher has stopped running or that fswatcher is not reporting any events. Could you try without `watch`?

**Comment by gdt** [comment] 2022-09-03 12:06
Given an attempt to reproduce and no further comments, I'm closing this.

@Alexander-Shukaev Feel free to read https://github.com/bcpierce00/unison/wiki/Reporting-Bugs-and-Feature-Requests and open a new issue with details, if you can reproduce with the most recent formal release or git master.

**Closed by gdt** 2022-09-03 12:06 UTC
Labels: defect, impact-high
