### ISSUE TITLE
Windows version hangs after completion?

### ISSUE THREAD

**Issue by xecrets** [bcpierce00/unison#279] opened 2019-08-29 08:26 UTC
Hi. Is it time for a new release?

I am running the latest release, 2.51.2, but that was released 18 months ago, and 'master' is now about 250 commits ahead...

I am having issues with this release, when synchronizing a large(?) amount of files.

Total directories: 640 000, total files 1 500 000.
Excluded via path exclusions: 360 000 directories and 1 000 000 files.

Effective totals is thus about 280 000 directories and 500 000 files.

Synchronization proceeds normally, until it appears that it is complete at which point the initiating Unison process drops it's memory usage to effectively zero (4 000 Kb) and then seem to just hang.

Neither process actually does anything, no IO, no CPU. It just sits there.

I have no idea if this is something that may be fixed by the updates since the release - but seeing as there seems to problems in building from source as well, it doesn't seem to be right way to go.

So... any plans for a new release soon? Or... any ideas of what the problem may be caused by?

**Comment by bcpierce00** [comment] 2019-08-29 13:37
You’re right that it is probably time for a release.  I am not set up to build on Windows myself, but if someone wants to build binaries I would love to make them available.

In the meantime, I believe building the text version of Unison from scratch should be straightforward, even on Windows — it’s just the GUIs that require more infrastructure.  I’d be interested to know whether this problem indeed persists in the current master or whether it’s been fixed in the meantime.

    - Benjamin

**Comment by xecrets** [comment] 2019-08-29 13:52
Thanks for quick response. Unfortunately (sort of) I've worked around it by running the synchronization a number of times - it succeeds partially, and then hangs as described. But since it gets something done each time, the set of changes is reduced and finally is manageable. (This implies that the problem is actually the size of the set of changes, not the size of the directory to synchronize itself that causes the problem).

I'll see if I can find some instructions that I can understand, on how to build on Windows, and if it doesn't require to much infrastructure installation.

But, right now, I don't have anything to really test against :-( .

**Comment by bcpierce00** [comment] 2019-08-29 13:58
The required infrastructure should be just the OCaml installation (and gnu make, I guess).  There should be people on the unison-users mailing list that can help.

**Comment by bbc2** [comment] 2019-09-06 17:37
I could compile the text interface for Windows by:

* Following the instructions at https://fdopen.github.io/opam-repository-mingw/installation/ and using the `ocaml-variants.4.08.1+mingw32c` compiler.
* Running `make OSTYPE=cygwin OSARCH=win32` (thanks to #159).

It's possible that I'm forgetting to mention some step I did because I initially failed a few times before finding the right compiler/MinGW combination, and I don't remember everything.

You can find the binary I compiled in this test release: https://github.com/bbc2/unison/releases/tag/win-test (SHA-256: e75f0a3979e86642e2c84a5ffb9066d98547ef1533b7b057968ff6e9b576527d), for commit 80133f36d670ed458a183857d98aa6bb19559b85.

I could synchronize files between my Windows VM and my Linux host so it looks like that binary works.

**Comment by rivy** [comment] 2020-09-29 01:48
@xecrets , I've got automated builds working (see [GH:rivy/unison/releases](https://github.com/rivy/unison/releases)). The most recent release (v2.51.3_rc1) is available for download. Once/if PR #380 is merged, builds should be automatically available for all future releases.

**Comment by gdt** [comment] 2020-10-13 22:57
This seems like #352

**Comment by gdt** [comment] 2022-02-13 16:52
This has no reproduction with recent unison, and seems like  a dup so I'm closing.   Feel free to reopen or new with a high-quality (debug logs), up-to-date report.

**Closed by gdt** 2022-02-13 16:52 UTC
Labels: defect, windows
