### ISSUE TITLE
Precompiled v2.52.0 for Windows crash

### ISSUE THREAD

**Issue by acsysch** [bcpierce00/unison#770] opened 2022-07-22 09:54 UTC
I tested several precompiled v2.52.0 versions on my Win10 machine, but all crash immediately. Regressed to v.2.51.1
[2022-07-22_11-51-57.pdf](https://github.com/bcpierce00/unison/files/9166693/2022-07-22_11-51-57.pdf)

**Comment by gdt** [comment] 2022-07-22 11:42
1) Please read thoroughly
https://github.com/bcpierce00/unison/wiki/Reporting-Bugs-and-Feature-Requests
and either provide the required information to show that this is a bug in unison, or close the bug and ask for help on unison-users@.

2) Note that 2.52.0 is not the most recent release, so bug  reports about it are not accepted.

**Comment by tleedjarv** [comment] 2022-07-22 12:04
Duplicate of #738.

**Closed** 2022-07-22 12:13 UTC
Labels: feedback
