### ISSUE TITLE
copy-on-conflict fails when file is deleted

### ISSUE THREAD

**Issue by TentativeConvert** [bcpierce00/unison#6] opened 2016-04-01 19:53 UTC
Using unison-2.48.3 in batch mode with the option 'copy on conflict', I obtain an error message when a file has been deleted in one repository and changed in another.

**Steps for reproducing the error**
1. Create a new file test.txt in 'local' folder.
2. Run unison, so that it copies this file to the 'remote' folder.
3. Delete the file test.txt in the 'remote' folder.
4. Edit the file test.txt in the 'local' folder (fill it with some content).
5. Run unison again, with the options

```
batch = true
prefer = newer
copyonconflict = true
```

I get the following error message:

```
UNISON 2.48.3 started propagating changes at 21:41:01.66 on 01 Apr 2016
[BGN] Copying test.txt from [[/home/localfolder]] to [[//server//home/remotefolder]]
100%  00:00 ETAUnison failed: Uncaught exception File "/build/unison-HIcI1m/unison-2.48.3/copy.ml", line 1007, characters 17-23: Assertion failed
Raised at file "/build/unison-HIcI1m/unison-2.48.3/copy.ml", line 1007, characters 17-29
Called from file "/build/unison-HIcI1m/unison-2.48.3/copy.ml", line 1010, characters 2-22
Called from file "/build/unison-HIcI1m/unison-2.48.3/files.ml", line 87, characters 4-55
Called from file "/build/unison-HIcI1m/unison-2.48.3/files.ml", line 311, characters 17-57
Called from file "/build/unison-HIcI1m/unison-2.48.3/remote.ml", line 764, characters 4-24
Called from file "/build/unison-HIcI1m/unison-2.48.3/lwt/lwt.ml", line 75, characters 20-23
Re-raised at file "/build/unison-HIcI1m/unison-2.48.3/lwt/lwt.ml", line 135, characters 12-13
Called from file "list.ml", line 73, characters 12-15
Called from file "/build/unison-HIcI1m/unison-2.48.3/lwt/lwt.ml", line 31, characters 2-37
Called from file "/build/unison-HIcI1m/unison-2.48.3/lwt/lwt.ml", line 83, characters 17-46
Called from file "/build/unison-HIcI1m/unison-2.48.3/lwt/generic/lwt_unix_impl.ml", line 147, characters 6-40
Called from file "/build/unison-HIcI1m/unison-2.48.3/main.ml", line 202, characters 6-24
Called from file "/build/unison-HIcI1m/unison-2.48.3/main.ml", line 131, characters 4-9
```

[Client and server both run 64-bit versions of Ubuntu 14.04 and use identical builds of unison-2.48.3.]

**Comment by bcpierce00** [comment] 2016-04-02 19:30
Thanks for the detailed instructions: I can reproduce the crash.  

What's happening is that the "copy" function in copy.ml is being asked to make a copy of a non-existent file on the remote side (because we're about to overwrite the conflicting deletion, and the copyonconflict flag is set). I think the best fix is just to change the "assert false" on line 1007 of copy.ml to "()" -- i.e., to silently ignore the instruction to copy a nonexistent path -- but I'm open to alternate suggestions.

**Comment by boyintello** [comment] 2017-04-18 11:14
Could you please update on how to do this on my mac, I am facing the same issue and would like to get rid of it.

**Comment by ndemou** [comment] 2017-07-03 14:04
@bcpierce00 the only alternate suggestion I can think of relies on this sentence "[the code] is being asked to make a copy of a non-existent file on the remote side ". So what about not asking? Is this possible/easier? But if this path of the code is only touched by this use-case your suggestion to silently ignore the error seems just fine (although I would suggest to log a warning instead of completely silencing).
Anyway I'm obviously also affected by this once a month on a complex use case[*] and would be happy to see this issue closed. BTW are there instructions on compiling unison for windows? I've managed to do it on Linux and I'll be forced to do it on windows if I want to get the fixes sooner than later.

Nick

*: I'm syncing a huge folder (many GBytes, tens of thousands of files, both sides rather active) between a Linux samba server and a Windows file server and another one between the same windows server and windows 7 workstation. I believe I've hit on more than the average number of issues because my connection is a high-latency and sometimes unstable satellite link. Overall unison mostly works fine but every week or two I'll stumble upon some issue and will have to manage it manually. Still thankful for your work but also wishing for something more-robust that could also handle the case where one side renames a directory with thousand of files gracefully. If you're curious, DFSR was working with no issues for about a year for the same folders and over the same connection (we moved to Unison after the H/W died).

**Comment by ndemou** [comment] 2017-07-03 20:24
I've had another case of this issue about 2 hours ago and I decided to think a bit deeper about what was my expectations from the synchronization algorithm. I'm posting my conclusions here:

Let's suppose that initially we begin from this state were ./dir/somefile.txt is synced between two hosts:

```
    host1:/dir/somefile.txt                                    [ver.1]
    host2:/dir/somefile.txt                                    [ver.1]
```

Now on host1 we update somefile.txt and on host2 we delete it so that we have this state:

```
    host1:/dir/somefile.txt                                    [ver.2]
    host2:/dir/                                              [DELETED]
```

After running unison with the options "batch = true, prefer = newer, copyonconflict = true" I expect it to produce this state:

```
    host1:/dir/somefile (conflict, deleted from host2 1/1/2017).txt  [ver.2]
    host2:/dir/somefile (conflict, deleted from host2 1/1/2017).txt  [ver.2]
```

I also expect unison to print a warning about the issue so that the person that gets mail about synchronization issues gets alerted (IMO one should not use the above unison options without having a way to get notifications about such warnings). Here's what the warning could look like:

`Warning: /dir/somefile.txt was changed on host1 and deleted on host2. Keeping a conflict copy on both sides.`

I should also note that this issue may also arise for directories. I expect the same behavior from Unison.

**Comment by ndemou** [comment] 2017-07-31 10:43
@bcpierce00 can you try your first thought (_I think the best fix is just to change the "assert false" on line 1007 of copy.ml to "()"_) and see what happens? The results may not be perfect but they could be better than the current situation.

**Comment by ndemou** [comment] 2017-10-12 19:07
@bcpierce00 I guess you don't have time for this and I can understand it. Do you think it's a manageable task for someone with zero knowledge of OCAml (that's me) to compile unison on windows and Linux? I'm writing large python programs and I've managed to compile Linux C utilities a few times but I don' consider myself experienced in this domain. However this bug is hitting me again and again and I'm close to give OCaml a try if you think it's not too much for my level.

**Comment by brabalan** [comment] 2017-10-13 06:58
@ndemou Compiling a text-only version of unison on linux is very simple, you only need to install ocaml with your package manager of choice. I've never done it on windows, but there are some instructions (see https://www.cis.upenn.edu/%7Ebcpierce/unison/download/releases/stable/unison-manual.html#build-win)

**Comment by ndemou** [comment] 2017-10-18 21:38
Many thanks @brabalan and sorry to all for not RTFM

**Comment by bcpierce00** [comment] 2017-10-20 15:58
Sorry for slow responses on this thread!  Do let us know what you learn...

**Comment by ericmsmythe** [comment] 2019-01-20 22:36
Hi Benjamin,
I spent some hours trying to deploy. Alas only one way sync works, however whenever I want to merge, I see an Assertion failure:
"UNISON 2.51.2 (OCAML 4.05.0) started propagating changes at 22:01:13.20 on 20 Jan 2019
Uncaught exception File "/home/eric/unison-2.51.2/src/path.ml", line 210, characters 4-10: Assertion failed"

I tried playing with the source and recompiling, but C is not my thing.
The above occurred with two small files in the same directory, my merge command in prefs file is:
merge = Name * -> diff3 -m CURRENT1 CURRENTARCH CURRENT2 > NEW

Here is the relevant source FWIW:
  with Not_found ->
    assert (not (isEmpty path));
    prefix ^ path

Any advice would be welcome,

Best wishes,
Eric

**Comment by tleedjarv** [comment] 2020-09-13 19:00
I thought I'd look into this one. It turns out that this bug was fixed already before this issue was reported in commit https://github.com/bcpierce00/unison/commit/5a5cf99bfb18dce8f7d8c76591b8110b9258bb99#diff-2a830ee6e028c8ce19c787701fc19c16 and then once more when this issue was reported, in commit https://github.com/bcpierce00/unison/commit/ed12af1f890623b4aff8b08316ca473a00ebf45e.

The bug itself is fixed and this issue should be closed (@glondu perhaps you can close it). Nevertheless, I tried to improve the behavior a bit as discussed here. Anyone interested, please feel free to test the solution in PR #373 to see if it meets your needs.

**Comment by gdt** [comment] 2020-09-14 14:29
Issue is reported as fixed - thanks for the update (and improvement PR!).

**Closed by gdt** 2020-09-14 14:29 UTC
Labels: effort-low, usability
