### ISSUE TITLE
When selecting multiple objects, actions are applied only to the first

### ISSUE THREAD

**Issue by mvglasow** [bcpierce00/unison#498] opened 2021-04-03 12:41 UTC
### To reproduce:

1. Set up a profile and synchronize.
2. Produce a large amount of differences in at least one copy.
3. Perform a scan using the GUI.
4. Using Shift, select multiple files from the list.
5. Click **Skip** (or any other action).

### Result observed:

The chosen action is applied to one single file (usually the first one selected).

### Result expected:

The chosen action is applied to all selected files.

### Versions:

2.51.3 on Windows 10; also observed with many earlier versions (and has probably been around from the very beginning).

**Comment by gdt** [comment] 2021-04-03 16:34
I labeled this as Windows only, pending someone saying it happens elsewhere.

**Comment by acolomb** [comment] 2021-04-04 18:57
I just tested on a Linux system (Ubuntu 20.04, Unison still at 2.48.4 for compatibility).  Changing multiple selected actions works with click-and-drag, click + shift-click, shift-downarrow, shift-pagedown.

Although I remember seeing this bug for several years already, I can't really say for sure if it ever happened on a non-Windows system.  Usually one of the other multiple-selection methods worked though, but rather tedious having to do the same selection twice.  I'll try to reproduce on Windows soon.

**Comment by acolomb** [comment] 2021-04-06 13:55
On Windows, I can reproduce with version 2.48.4.  Multiple-selection with click-and-drag works, the other methods show the behavior described here.  GTK was installed from [Chocolatey](https://community.chocolatey.org/packages/gtk-runtime), same as [Unison](https://community.chocolatey.org/packages/unison/2.48.4).

More precisely, after releasing the shift key in any of those combos, the tree view does not respond properly to arrow keys anymore.  Up / down do nothing, left / right manipulate only the first selected line.  Clicking on a different line (without holding shift again) works as though the key was still held, i.e. selecting from the original line to the one clicked, then restores normal behavior for the arrow keys.  So I'd say it smells like some key-release event or similar is not being handled properly.

It's rather hard to test such stuff under Windows, because of the complicated build process involving GTK for the GUI.  Pre-built GTK2 binaries were mostly outdated last time I searched for them, like the six-year-old version on Chocolatey.  Does anyone know where to get those, as this might just as well be a GTK runtime bug?

**Comment by mvglasow** [comment] 2021-04-06 14:33
I got my Windows copy from https://github.com/bcpierce00/unison/releases and did not have to install any extra GTK run-time components. However, I use 2.51.3 on Windows; not sure if the same is true for previous versions, especially those built before the project started using Github Actions.

As for getting GTK for Windows, maybe the CI script at https://github.com/bcpierce00/unison/blob/master/.github/workflows/CICD.yml provides some clues? It is how the releases on Github get built (starting with 2.51.3-rc2).

**Comment by tleedjarv** [comment] 2021-06-26 19:58
Incidentally, #557 seems to fix this issue.

**Comment by gdt** [comment] 2021-06-27 11:54
Retesting on 2.51.4 would be appreciated.

**Comment by gdt** [comment] 2022-05-28 13:08
@mvglasow Please test with master, which has switched to gtk3.

**Comment by tleedjarv** [comment] 2022-09-02 07:57
Propose to close this. There has been no confirmation that this issue is present beyond 2.51.3, yet there is anecdotal evidence that things work since 2.51.4.

**Comment by gdt** [comment] 2022-09-02 12:24
It seems more likely than not that this is fixed, and a retest request has timed out.  Please feel free to open a new issue if you can reproduce this against master (we're heading for release, so the latest formal release, while formally valid for reporting against, is going to be old in not that long).

**Closed by gdt** 2022-09-02 12:24 UTC
Labels: defect, effort-high, impact-low, GUI, feedback, windows
