### ISSUE TITLE
False conflicts, and nonidentical archives

### ISSUE THREAD

**Issue by benyanke** [bcpierce00/unison#98] opened 2017-10-04 22:23 UTC
`Fatal error: Internal error: On-disk archives are not identical.`

I'm getting this error every few weeks in my long-running sync job (about 8 unison instances syncing a combined 2TB, made up of roughly 1.2 million files). Both on unison version 2.48.3.

I am unsure where to begin debugging, since it only occurs about every month or two. I have everything still in place, so I can look at the archives and such. The other symptom which frequently occurs is false-duplicates: I am getting copies of multiple files, usually in grouped batches, when one of the two servers  being synced were not modifying anything. I'm unsure if this related, but the timing of all these things seems to say they're related.

I am hoping to use this in a production system very soon, so I am hoping I can work out these errors.

This also appeared in my logs directly above one of the archive errors. I'm not sure if this is related:
```
unison-instance-logs/recent-phone-orders-batch-4.log-Uncaught exception File "/build/unison-WhGSf0/unison-2.48.3/copy.ml", line 1007, characters 17-23: Assertion failed
unison-instance-logs/recent-phone-orders-batch-4.log-Raised at file "/build/unison-WhGSf0/unison-2.48.3/lwt/lwt.ml", line 126, characters 22-23
unison-instance-logs/recent-phone-orders-batch-4.log-Called from file "/build/unison-WhGSf0/unison-2.48.3/lwt/generic/lwt_unix_impl.ml", line 102, characters 8-23
unison-instance-logs/recent-phone-orders-batch-4.log-Called from file "/build/unison-WhGSf0/unison-2.48.3/uitext.ml", line 490, characters 2-113
unison-instance-logs/recent-phone-orders-batch-4.log-Called from file "/build/unison-WhGSf0/unison-2.48.3/uitext.ml", line 556, characters 38-66
unison-instance-logs/recent-phone-orders-batch-4.log-Called from file "/build/unison-WhGSf0/unison-2.48.3/uitext.ml", line 718, characters 6-47
unison-instance-logs/recent-phone-orders-batch-4.log-Called from file "/build/unison-WhGSf0/unison-2.48.3/uitext.ml", line 788, characters 6-90
unison-instance-logs/recent-phone-orders-batch-4.log-Called from file "/build/unison-WhGSf0/unison-2.48.3/uitext.ml", line 810, characters 19-66
unison-instance-logs/recent-phone-orders-batch-4.log-Called from file "/build/unison-WhGSf0/unison-2.48.3/uitext.ml", line 870, characters 21-43

```

**Comment by benyanke** [comment] 2017-10-04 22:24
Also, currently one workaround I see is deleting the archives periodically (perhaps nightly or weekly) and rescanning again from scratch. This is sub-par, but could potentially work.

**Comment by brabalan** [comment] 2017-10-05 07:08
The error in the log comes from a file that is supposed to be copied from one place to another that is absent. I'm surprised we have an `assert false` there. This might be the cause of the archives being different.

**Comment by bcpierce00** [comment] 2017-11-27 17:09
The code in the master branch has been changed to this:

      | `ABSENT ->
          (* BCP 4/16: Was "assert false", but this causes unison to
             crash when (1) the copyonconflict preference is used, (2) 
             there is a conflict between a deletion and a change, and
             (3) the change is propagated on top of the deletion.  Seems
             better to silently ignore the copy request. *)
          ()

**Comment by benyanke** [comment] 2017-11-28 07:53
I will upgrade and try. May be a while, as this project got pushed down my priority list since this bug caused me to go another route in the short term and not use unison yet.

**Comment by bcpierce00** [comment] 2017-11-28 11:38
OK, let us know when you know.  I'm closing this issue for now.

**Closed by bcpierce00** 2017-11-28 11:38 UTC
Labels: fixed now?
