### ISSUE TITLE
Add macOS Unison.App to build system and CI build

### ISSUE THREAD

**Issue by grahampugh** [bcpierce00/unison#422] opened 2020-11-04 10:17 UTC
Hi, apologies if I'm missing something obvious, but the 2.51.2 release for macOS was an application. 2.51.3 appears to be just the binaries. Is there still an intention to release a compiled application? Since I am tasked with deploying to managed Macs, we don't support Homebrew etc. as these tools are not very compatible and often interfere with enterprise management systems.

**Comment by gdt** [comment] 2020-11-04 12:56
Please note that the tracker is only for bugs and enhancement requests; questions belong on the mailing list.

I have edited the title to make it a feature request.  Pull requests welcome, and discussion of approach if controversial should be on unison-hackers.

**Comment by grahampugh** [comment] 2020-11-04 17:58
It's not really an enhancement request so much as a non-regression request. There was an app provided, and now there isn't. Specifically, I wondered if it was a bug/mistake to not provide an app, or just an undocumented change? 

Also the link to pre-packaged binaries (http://www.cis.upenn.edu/~bcpierce/unison) in the README just loops back to here again, presumably also not intended.

**Comment by tleedjarv** [comment] 2020-11-04 20:56
There are regressions building Unison.app. Meanwhile, I managed to get a working build with OCaml 4.07.1. Go to https://github.com/bcpierce00/unison/actions/runs/346271089 and download the artifact with suffix `.app` to test this out. I don't have access to a Mac so I don't know if it actually works or it just builds.

**Comment by bunk3m** [comment] 2020-11-04 22:51
I gave the app build a try and get `Unison.app is damaged and can't be opened. You should move it to the trash.`
I do see that it says 10.15 and I'm running 10.14.6 so this could be the problem.  I won't be updating to 10.15 anytime soon.
Is it possible to compile with target 10.14.6 so we can remove that as an issue?

**Comment by tleedjarv** [comment] 2020-11-05 09:08
> Is it possible to compile with target 10.14.6 so we can remove that as an issue?

I don't think GHA virtual environments have 10.14 SDK.

**Comment by grahampugh** [comment] 2020-11-05 09:39
Hi all,
Thanks for your efforts. Unfortunately the app at https://github.com/bcpierce00/unison/actions/runs/347177040 will not open on macOS 10.15.7.

```
Nov  5 10:24:05 mycomputer com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000003e.Unison[4231]): Could not find and/or execute program specified by service: 13: Permission denied: /Applications/Unison 2.app/Contents/MacOS/Unison
Nov  5 10:24:05 mycomputer com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000003e.Unison[4231]): Service exited with abnormal code: 78
``` 

This was solved by adding execute permissions to the binaries:

```
sudo chmod -R +x /Applications/Unison\ 2.app/Contents/MacOS
```

But then we get a warning that the app is damaged.

![Screenshot 2020-11-05 at 10 28 10](https://user-images.githubusercontent.com/5802725/98222839-a7070800-1f51-11eb-80b9-1d2759f457f0.png)

This is due to the app not being signed and notarised. This can be manually overcome using the following command, which removes the extended attribute that is added when downloading an app via the internet:

```
xattr -cr /Applications/Unison\ 2.app 
```

### Conclusion

The permissions error on the items in the `/Contents/MacOS` folder should be fairly easily addressed.

To make the app easily available for individual downloads, it would need to be signed and notarised using an Apple Developer ID. This is less of a problem in macOS management systems, which generally use `curl` to obtain the app, package it up and use `installer` to install the package on clients. This method of installation does not currently add the extended attribute to the app, so it will run without manual intervention.

**Comment by tleedjarv** [comment] 2020-11-05 10:38
The lack of execute permissions is a side-effect of the GHA workflow (see https://github.com/actions/upload-artifact#permission-loss). This will be fixed with proper packaging for releases.

**Comment by tleedjarv** [comment] 2020-11-05 10:40
> This is due to the app not being signed and notarised. This can be manually overcome using the following command

After setting execute permission and removing the extended attribute, does the app start and work?

**Comment by grahampugh** [comment] 2020-11-05 10:41
> After setting execute permission and removing the extended attribute, does the app start and work?

The app starts, and I was able to install the CLI tools via the GUI. I haven't actually tried to use it to sync any files.

**Comment by ryandesign** [comment] 2020-11-05 22:20
> > Is it possible to compile with target 10.14.6 so we can remove that as an issue?
> 
> I don't think GHA virtual environments have 10.14 SDK.

That's irrelevant. You can build an app on the latest version of macOS using the latest SDK that nevertheless can run on an earlier version of macOS (the "deployment target").

**Comment by gdt** [comment] 2020-11-06 00:10
Your comment complaining that other people have not done what you want is missing a link to the pull request where you provide the code :-)

**Comment by bunk3m** [comment] 2020-11-06 03:59
Thank you for identifying the command to get Unison to start-up. 

`xattr -cr /Applications/Unison.app` works.

To open without the Apple dev signature you can ctrl+click to open the menu. In the menu select "Open". THen you get a question if you want to open the app.  Select affirmative and the app will open without error.

I'm in the process of testing some sync with my server and will report back.

**Comment by bunk3m** [comment] 2020-11-06 04:04
OK, it looks like the app runs OK once the changes above have been made.  I am running it on 10.14.6 without issue so far.  I've run a half dozen syncs to my server.
I still have problems with props changing but I believe that is a setting that I have not figured out.
Thanks!

**Comment by gdt** [comment] 2020-11-06 13:48
> Also the link to pre-packaged binaries (http://www.cis.upenn.edu/~bcpierce/unison) in the README just loops back to here again, presumably also not intended.

That is intended.  The binaries formerly referenced from the UPenn page are all ancient.

My view is that what matters is the contents of the source repo as tagged for releases, so any former build/publish processes for binaries not based on code in the repo, while a welcome contribution to the community, are out of scope to me.  I don't mean they aren't useful examples, just that any instructions/etc. should become code/scripts and in the repo.

It does seem like this is now partly fixed and awaiting more testing from people.

**Comment by tleedjarv** [comment] 2020-11-06 17:19
> You can build an app on the latest version of macOS using the latest SDK that nevertheless can run on an earlier version of macOS (the "deployment target").

Looking at the Makefile and xcodeproj, it does seem like the deployment target is currently set as 10.6.

**Comment by bunk3m** [comment] 2020-11-06 17:56
> > You can build an app on the latest version of macOS using the latest SDK that nevertheless can run on an earlier version of macOS (the "deployment target").
> 
> Looking at the Makefile and xcodeproj, it does seem like the deployment target is currently set as 10.6.

That will certainly cover off 99.9% of all possible MacOS variants in service.

**Comment by tleedjarv** [comment] 2020-11-08 21:05
Please download an artifact from https://github.com/bcpierce00/unison/actions/runs/352740603
Inside the zip file is the actual archive that will be available for download on the releases page (that is, it will not be wrapped in a zip file once released). Please test if this archive works as you'd expect. Is this a suitable input for autopkg?

**Comment by bunk3m** [comment] 2020-11-09 03:53
Hello.  I downloaded each of the `Unison-09393f26.ocaml-4.xx.y.macos-10.15.app` versions and tried to run by double clicking after moving the /Applications/ folder.
Each one needed the command `xattr -ca Unison.app` in order to be able to start up.  Once the command was run, right click and "Open" and it runs.

**Comment by gdt** [comment] 2020-11-09 11:32
The user's computer sets com.apple.quarantine at download, so that sounds as good as it is going to get!

**Comment by grahampugh** [comment] 2020-11-09 12:30
@tleedjarv 
>Is this a suitable input for autopkg?

Unfortunately I'm struggling to find a method by which `curl` will return the same HTML contents as are shown in the GUI from https://github.com/bcpierce00/unison/actions/runs/352740603 so I haven't yet found a method by which I can download the `.app` using curl. This is the only way I'm going to avoid the quarantine flag, which would then provide a realistic test for AutoPkg.

Do you know if the GitHub API includes options for obtaining artefact downloads and not just releases?

**Comment by tleedjarv** [comment] 2020-11-09 15:17
Yes, the artifacts are only accessible when you're logged in. But you need to extract tar.gz from the zip file anyway and feed the former to AutoPkg.

If you want to test with a github URL then a wild idea is that first download from the artifacts page, extract, then add the tar.gz file as an attachment to your comment here or in the autopkg repo. Downloading comment's attachment should then be possible directly. You could try :-)

**Comment by grahampugh** [comment] 2020-11-09 16:04
Interesting idea, I'll give it a try. 
AutoPkg can handle zipped gzipped tars. It's just tokens it can't handle :)

**Comment by grahampugh** [comment] 2020-11-09 16:26
It works :) 
By putting the app in a package (normal procedure for AutoPkg), and installing the package, there are no attribute/quarantine problems and the app opens normally.
https://github.com/autopkg/grahampugh-recipes/blob/unison-temp/Unison/Unison.pkg.recipe

**Comment by gdt** [comment] 2020-11-20 20:25
fix merged!

**Closed by gdt** 2020-11-20 20:25 UTC
Labels: effort-high, enhancement, macOS
